Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Controllers/PredictionHistoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Amazon;
using Amazon.S3;
using DataAccess.ViewModels;
using Hld.WebApplication.Helper;
using Hld.WebApplication.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using PagedList.Core;

namespace Hld.WebApplication.Controllers
{
    [TokenExpires]
    public class PredictionHistoryController : Controller
    {
        private IHostingEnvironment _hostingEnvironment;
        private AmazonS3Client _s3Client = new AmazonS3Client(RegionEndpoint.USEast2);
        private string _bucketName = "jobsfilesbucket";//this is my Amazon Bucket name
        private static string _bucketSubdirectory = "ASINSKUMapping-Jobs";
        //private static string _Ds_Qty_CommentsSubdirectory = "Ds_Qty_Comments";
        //private static string _ImportMissingSkuSubdirectory = "MissingSKUFromSellerCloud";

        string ApiURL = "";
        string token = "";
        int POMasterID = 0;
        string s3BucketURL = "";
        string s3BucketURL_large = "";
        string SCRestURL = "";
        EncDecChannel _encDecChannel = null;
        GetChannelCredViewModel _Selller = null;
        PredictionHistoryApiAccess _ApiAccess = null;
        OrderNotesAPiAccess _OrderApiAccess = null;

        private readonly Microsoft.Extensions.Logging.ILogger logger;
        UploadFilesToS3ForJobsAPIAccess ApiAccess = null;
        private readonly IConfiguration _configuration;
        public PredictionHistoryController(IConfiguration configuration, IHostingEnvironment environment, ILogger<PredictionHistoryController> _logger)
        {
            _hostingEnvironment = environment;
            this._configuration = configuration;
            s3BucketURL = _configuration.GetValue<string>("S3BucketURL:URL");
            s3BucketURL_large = _configuration.GetValue<string>("S3BucketURL:L_URL");
            ApiURL = _configuration.GetValue<string>("WebApiURL:URL");
            ApiAccess = new UploadFilesToS3ForJobsAPIAccess();
            this.logger = _logger;
            _ApiAccess = new PredictionHistoryApiAccess();
            _OrderApiAccess = new OrderNotesAPiAccess();
            SCRestURL = _configuration.GetValue<string>("WebApiURL:SCRestURL");
            _encDecChannel = new EncDecChannel();
        }

        public IActionResult Index(HistorySearchViewModel viewModel)
        {
            string token = Request.Cookies["Token"];
            bool Approved = false;
            bool Excluded = false;
            bool Continue = false;
            bool KitShadowStatus = false;
            if (!string.IsNullOrEmpty(viewModel.ItemType) && viewModel.ItemType != "undefined")
            {
                string[] Val = viewModel.ItemType.Split(',');
                int length = Val.Length;
                foreach (var item in Val)
                {
                    if (item == "Approved")
                    {
                        Approved = true;
                    }
                    if (item == "Excluded")
                    {
                        Excluded = true;
                    }
                    if (item == "Continue")
                    {
                        Continue = true;
                    }
                    if (item == "KitShadowStatus")
                    {
                        KitShadowStatus = true;
                    }

                }
            }

            if (viewModel.VendorId != 0 )
            {
                POMasterID = viewModel.VendorId;
            }
            else
            {
                POMasterID = Convert.ToInt32(Request.Cookies["POMasterID"]);
            }
            if (!string.IsNullOrEmpty(viewModel.SearchFromSkuListPredict))
            {
                var lines = viewModel.SearchFromSkuListPredict.Split(new[] { '\r', '\n' }, StringSplitOptions.RemoveEmptyEntries);
                string newLines = string.Join(",", lines);
                viewModel.SearchFromSkuListPredict = getString(newLines);
                string skuList = JsonConvert.SerializeObject(viewModel.SearchFromSkuListPredict);
                HttpContext.Session.SetString("skuList", skuList);
               
                ViewBag.skuSearchList = "searchList";
            }
            else
            {
                viewModel.SearchFromSkuListPredict = "Nill";
                ViewBag.skuSearchList = "";
            }
            var Count = _ApiAccess.PredictionSummaryCount(ApiURL, token, POMasterID, viewModel.SKU, viewModel.Title, Approved,Excluded, KitShadowStatus,Continue, viewModel.SearchFromSkuListPredict, viewModel.Type);
            ViewBag.TotalCount = Count;
            return View(viewModel);
        }

        public IActionResult PredictionDetail(int? page, string SKU, string Title, int VendorId, string Sort, string SortedType, string ItemType = "", int Type = 0)
        {
            string token = Request.Cookies["Token"];
            var key = HttpContext.Session.GetString("skuList");
            bool Approved = false;
            bool Excluded = false;
            bool Continue = false;
            bool KitShadowStatus = false;

           

            if (!string.IsNullOrEmpty(ItemType) && ItemType != "undefined")
            {
                string[] Val = ItemType.Split(',');
                int length = Val.Length;
                foreach (var item in Val)
                {
                    if (item == "Approved")
                    {
                        Approved = true;
                    }
                    if (item == "Excluded")
                    {
                        Excluded = true;
                    }
                    if (item == "Continue")
                    {
                        Continue = true;
                    }
                    if (item == "KitShadowStatus")
                    {
                        KitShadowStatus = true;
                    }

                }
            }
           
            IPagedList<PredictionHistroyViewModel> data = null;
            int pageNumber = page.HasValue ? Convert.ToInt32(page) : 1;
            int pageSize = 50;
            int offset = 0;
            
            int startlimit = pageSize;
            if (page.HasValue)
            {
                offset = (pageNumber - 1) * pageSize;
                ViewBag.pageNumber = page.Value;
            }
            if (VendorId != 0)
            {
                POMasterID = VendorId;
            }
            else
            {
                POMasterID = Convert.ToInt32(Request.Cookies["POMasterID"]);
            }
           
            if (!string.IsNullOrEmpty(key))
            {
                string skuList = JsonConvert.DeserializeObject<string>(key);
                List<PredictionHistroyViewModel> listmodels = new List<PredictionHistroyViewModel>();
                listmodels = _ApiAccess.GetPredictionDetailCopy(ApiURL, token, startlimit, offset, skuList);
                data = new StaticPagedList<PredictionHistroyViewModel>(listmodels, pageNumber, pageSize, listmodels.Count);
                
                ViewBag.S3BucketURL = s3BucketURL;
                ViewBag.S3BucketURL_large = s3BucketURL_large;
                HttpContext.Session.Remove("skuList");
                ViewBag.skuSearchList = "searchList";
                return PartialView("~/Views/PredictionHistory/PredictionDetail.cshtml", data);

            }
            if (string.IsNullOrEmpty(SKU))
                SKU = "undefined";
            if (string.IsNullOrEmpty(Title))
                Title = "undefined";
            List<PredictionHistroyViewModel> listmodel = new List<PredictionHistroyViewModel>();
            listmodel = _ApiAccess.GetPredictionDetail(ApiURL, token, startlimit, offset, POMasterID, SKU, Title, Approved, Excluded, KitShadowStatus, Continue, Sort, SortedType, Type);
            data = new StaticPagedList<PredictionHistroyViewModel>(listmodel, pageNumber, pageSize, listmodel.Count);
           
            ViewBag.S3BucketURL = s3BucketURL;
            ViewBag.S3BucketURL_large = s3BucketURL_large;
          
            return PartialView("~/Views/PredictionHistory/PredictionDetail.cshtml", data);
        }

        public IActionResult SkuSelectListPredict()
        {
            return PartialView("~/Views/PredictionHistory/_skuSelectListPredict.cshtml");
        }
        public string getString(string text)
        {
            if (!string.IsNullOrEmpty(text))
            {
                //   '\'apple\',\'banana\''
                string finalString = "";
                string[] splitString = text.Split(',');

                int end = splitString.Length - 1;
                StringBuilder stringBuilder = new StringBuilder();

                if (!(splitString.Length > 1))
                {
                    stringBuilder.Append(string.Concat("\'", splitString[0] + "\'"));
                }
                else
                {
                    for (int i = 0; i < splitString.Length; i++)
                    {
                        stringBuilder.Append(string.Concat("\'", splitString[i] + "\',"));
                    }
                }
                int index = stringBuilder.ToString().LastIndexOf(',');
                if (index != -1)
                {
                    finalString = stringBuilder.ToString().Remove(index);
                }
                else
                {
                    finalString = stringBuilder.ToString();
                }

                return finalString;
            }
            else
            {
                return "";
            }
        }
        public int Save(PredictionPOViewModel data)
        {
            token = Request.Cookies["Token"];

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/PredictionHistory/DraftPO.cshtml
@model IEnumerable<Hld.WebApplication.ViewModel.DraftPOViewModel>

@{
    ViewData["Title"] = "DraftPO";
    Layout = "~/Views/Shared/_LayoutNavigation.cshtml";
}
<style>
    .table {
        border-left: #ccc 1px solid !important;
        border-right: #ccc 1px solid !important;
    }

        .table thead tr th {
            /*position: sticky;
            top: 169px;
            padding: 5px;
            z-index: 2;*/
            background-color: lightgray !important;
        }

    .tablesorter-default .tablesorter-header {
        outline: none !important;
    }
</style>

<div class="container-fluid searchFormFixed">
    <div class="col-md-12">
        <br />
        <h6>Draft PO</h6>

    </div>
    <div class="col-md-12">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Internal PO #
                    </th>
                    <th>
                        Vendor
                    </th>
                    <th>
                        SKUs
                    </th>

                    <th>
                        Notes
                    </th>
                    <th>
                        Created On
                    </th>

                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <a href="../PredictionHistory/PredictionListDummy?data=@item.InternalPOId" target="_blank" style="cursor:pointer">@item.InternalPOId</a>
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Vendor)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.SKUs)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Notes)
                        </td>
                        <td>
                            @if (item.OrderedOn != DateTime.MinValue)
                            {
                                @string.Format("{0: MMM d, yyyy}", item.OrderedOn)
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/sticky-table-headers/js/jquery.stickytableheaders.min.js"></script>
    <script src="~/lib/jQuery-Paging/jquery.paging.min.js"></script>
    <script src="~/lib/jQuery-MultiSelect/jquery.multiselect.js"></script>
    <script src="~/select2/js/select2.full.min.js"></script>

    <script src="~/lib/date-range-picker/moment.min.js"></script>
    <script src="~/lib/date-range-picker/daterangepicker.js"></script>

    <script src="~/lib/jquery.tablesorter/js/jquery.tablesorter.min.js"></script>
    <script>
        $(document).ready(function () {

            $(".table").tablesorter();
        });
</script>
}

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/PredictionHistory/PredictionPartialView.cshtml
@{
    ViewData["Title"] = "WatchListSummary";
    Layout = "~/Views/Shared/_LayoutNavigation.cshtml";

}
@*<link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">*@
<link href="~/boots/bootstrap-toggle.min.css" rel="stylesheet" />

<style>
   

    .pagination > a {
        padding: 5px;
    }

   
    
</style>

<div class="container-fluid ">
    <div class="loader">
        <img src="~/Images/giffff.gif" />
    </div>
    <div class="container-fluid">

        <div class="row col col-12" id="fixActionMenu">
            <div class="col col-md-2">
                <div class="row" style="">
                    <div class="pagination col-md-6 col">

                    </div>

                </div>
            </div>
            <div class="col col-md-2" style="">
                <span>Records Found : @ViewBag.Records</span>
            </div>


        </div>
    </div>
    <div class="container-fluid">
        <div id="loadOrder">

        </div>
    </div>
    <div class="container-fluid">
        <div class="pagination" style="">

        </div>
    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/jQuery-Paging/jquery.paging.min.js"></script>
    @*<script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>*@
    <script src="~/lib/bootstrap-toggle.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
          
          //pagination
    $(".pagination").paging(parseInt('@ViewBag.Records'), {
    format: '[< nncnn >]',
    perpage: 25, // show 10 elements per page
    lapping: 0, // don't overlap pages for the moment
    page: 1, // start at page, can also be "null" or negative
    stepwidth: 0, // =0 means blockwise next/prev steps
    onSelect: function (page) {

    pageNo = page;
    // add code which gets executed when user selects a page
        var completURL = '/PredictionHistory/PredictionDetail?page=' + page + ''

    $(".loadertbl").show();

        $.ajax({
            url: completURL,
            data: {},
            type: 'POST',
            traditional: true,
            success: function (data) {
                $('#loadOrder').empty();
                $('#loadOrder').html(data);
                $(".loadertbl").hide();
             
            }
        });
     
    },
        onFormat: function (type) {
            switch (type) {
                case 'block': // n and c
                    if (this.page === this.value) {
                        return '<span>' + this.value + '</span>';
                    } else {
                        return '<a href="#">' + this.value + '</a>';
                    }
                case 'next': // >
                    return '<a href="#">&gt;</a>';
                case 'prev': // <
                    return '<a href="#">&lt;</a>';
                case 'first': // [
                    return '<a href="#">First</a>';
                case 'last': // ]
                    return '<a href="#">Last</a>';
            }
        }


    });
             
    });
    </script>
}

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/PredictionHistory/_skuSelectListPredict.cshtml
@model HistorySearchViewModel
<div>
    <form asp-action="Index" asp-controller="PredictionHistory" role="form">

        <div class="form-group row">
            <div class="col-md-8">
                <input name="EmptyFirstTime" id="EmptyFirstTime" value="No" style="display:none" />
                <textarea id="SearchFromSkuListPredict" name="SearchFromSkuListPredict" style="padding-left:4px;margin-right: -26px;" cols="50" rows="10"></textarea>
             
            </div>
            <div class="col-md-4">
                <span id="countsku" style="bottom: 0; position: absolute;margin-left: -42px;"></span>

            </div>

        </div>
        <span class="text-danger" asp-validation-for="SearchFromSkuListPredict"></span>
        <input type="submit" id="SearchFromSkuListPredict" value="Search" class="btn btn-primary" />
    </form>
</div>