Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Controllers/BestBuyDropshipQtyMovementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Hld.WebApplication.ViewModel;
using Hld.WebApplication.Helper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using MySql.Data.MySqlClient;
using System.Data;
using System.Collections.Specialized;
using System.Web;
using Newtonsoft.Json;
using Microsoft.AspNetCore.Http;
using PagedList;

namespace Hld.WebApplication.Controllers
{

    [TokenExpires]
    public class BestBuyDropshipQtyMovementController : Controller
    {
        private readonly IConfiguration _configuration;
        string ApiURL = "";
        string token = "";
        string connectionString = "";


        BestBuyDropshipQtyMovementApiAccess _dropshipQtyMovementApiAccess = null;
        public BestBuyDropshipQtyMovementController(IConfiguration configuration)
        {
            this._configuration = configuration;
            ApiURL = _configuration.GetValue<string>("WebApiURL:URL");
            connectionString = _configuration.GetValue<string>("ConnectionString:bb2HldNet");
            _dropshipQtyMovementApiAccess = new BestBuyDropshipQtyMovementApiAccess();

        }
        public IActionResult Index()
        {
            return View();
        }

        public ActionResult AllDropshipQtyMovementList()
        {

            return View();
        }
        public IActionResult GetQtyLogs()
        {
            var querystring = Request.QueryString;
            string dynamicQueryGeneration = "";
            List<BestBuyQTYLogsDetailViewModel> listModel = null;
            NameValueCollection query = HttpUtility.ParseQueryString(Request.QueryString.Value);
            var filtersCount = int.Parse(query.GetValues("filterscount")[0]);
            if (filtersCount > 0)
            {
                dynamicQueryGeneration = BuildLOgsQuery(querystring);
                listModel = GetQtyLogsDynamicQuery(dynamicQueryGeneration);


            }
            else
            {

                listModel = LogsData();


            }

            return Json(listModel);
        }

        private string BuildLOgsQuery(QueryString queryStringField)
        {
            NameValueCollection query = HttpUtility.ParseQueryString(queryStringField.Value);
            var filtersCount = int.Parse(query.GetValues("filterscount")[0]);
            var queryString = @"SELECT 
`BestBuyDropsShipQtyMovement`.`product_sku`,ds_qty,ifnull(order_qty,0) ,ifnull(BestBuyProducts.product_sku,'') BBProductID,
case when ds_status=false then 'Dropship None'  else 'DropShip' End  as ds_status ,    
`BestBuyDropsShipQtyMovement`.`order_date`,
case when `BestBuyDropsShipQtyMovement`.`is_ds_status_updated_id`=1 then 'Updated' else 'Pending' end as update_status,
`BestBuyDropsShipQtyMovement`.`bb_import_id` ,ifnull(dropship_comments,'') as comments
FROM `bestBuyE2`.`BestBuyDropsShipQtyMovement`
inner join BestBuyProducts  
on BestBuyProducts.shop_sku_offer_sku=`bestBuyE2`.`BestBuyDropsShipQtyMovement`.product_sku";
            var tmpDataField = "";
            var tmpFilterOperator = "";
            var where = "";
            if (filtersCount > 0)
            {
                where = " WHERE (";
            }
            for (var i = 0; i < filtersCount; i += 1)
            {
                var filterValue = query.GetValues("filtervalue" + i)[0];
                var filterCondition = query.GetValues("filtercondition" + i)[0];
                var filterDataField = query.GetValues("filterdatafield" + i)[0];
                var filterOperator = query.GetValues("filteroperator" + i)[0];
                if (tmpDataField == "")
                {
                    if (filterDataField == "update_status")
                    {
                        filterDataField = "is_ds_status_updated_id";
                    }
                    if (filterDataField == "product_sku")
                    {
                        filterDataField = "`BestBuyDropsShipQtyMovement`.`product_sku`";
                    }
                    if (filterDataField == "comments")
                    {
                        filterDataField = "`dropship_comments`";
                    }
                    tmpDataField = filterDataField;
                }
                else if (tmpDataField != filterDataField)
                {
                    where += ") AND (";
                    if (filterDataField == "update_status")
                    {
                        filterDataField = "is_ds_status_updated_id";
                    }
                    if (filterDataField == "product_sku")
                    {
                        filterDataField = "`BestBuyDropsShipQtyMovement`.`product_sku`";
                    }
                    if (filterDataField == "comments")
                    {
                        filterDataField = "`dropship_comments`";
                    }
                }
                else if (tmpDataField == filterDataField)
                {
                    if (tmpFilterOperator == "0")
                    {
                        where += " AND ";
                    }
                    else
                    {
                        where += " OR ";
                    }
                }
                // build the "WHERE" clause depending on the filter's condition, value and datafield.
                where += this.GetFilterQtyCondition(filterCondition, filterDataField, filterValue);
                if (i == filtersCount - 1)
                {
                    where += ")";
                }
                tmpFilterOperator = filterOperator;
                tmpDataField = filterDataField;
            }
            queryString += where;
            return queryString;
        }

        private string GetFilterQtyCondition(string filterCondition, string filterDataField, string filterValue)
        {
            switch (filterCondition)
            {
                case "NOT_EMPTY":
                case "NOT_NULL":
                    return " " + filterDataField + " NOT LIKE '" + "" + "'";
                case "EMPTY":
                case "NULL":
                    return " " + filterDataField + " LIKE '" + "" + "'";
                case "CONTAINS_CASE_SENSITIVE":
                    return " " + filterDataField + " LIKE '%" + filterValue + "%'" + "  ";
                case "CONTAINS":
                    return " " + filterDataField + " LIKE '%" + filterValue + "%'";
                case "DOES_NOT_CONTAIN_CASE_SENSITIVE":
                    return " " + filterDataField + " NOT LIKE '%" + filterValue + "%'" + "  "; ;
                case "DOES_NOT_CONTAIN":
                    return " " + filterDataField + " NOT LIKE '%" + filterValue + "%'";
                case "EQUAL_CASE_SENSITIVE":
                    return " " + filterDataField + " = '" + filterValue + "'" + "  "; ;
                case "EQUAL":
                    return " " + filterDataField + " = '" + filterValue + "'";
                case "NOT_EQUAL_CASE_SENSITIVE":
                    return " BINARY " + filterDataField + " <> '" + filterValue + "'";
                case "NOT_EQUAL":
                    return " " + filterDataField + " <> '" + filterValue + "'";
                case "GREATER_THAN":
                    return " " + filterDataField + " > '" + filterValue + "'";
                case "LESS_THAN":
                    return " " + filterDataField + " < '" + filterValue + "'";
                case "GREATER_THAN_OR_EQUAL":
                    if (filterDataField == "order_date")
                    {
                        return "convert( " + filterDataField + ",date) >= '" + filterValue + "'";
                    }
                    else
                    {
                        return " " + filterDataField + " >= '" + filterValue + "'";
                    }
                case "LESS_THAN_OR_EQUAL":
                    if (filterDataField == "order_date")
                    {
                        return "convert( " + filterDataField + ",date) <= '" + filterValue + "'";
                    }
                    else
                    {
                        return " " + filterDataField + " <= '" + filterValue + "'";
                    }

                case "STARTS_WITH_CASE_SENSITIVE":
                    return " " + filterDataField + " LIKE '" + filterValue + "%'" + "  ";
                case "STARTS_WITH":
                    return " " + filterDataField + " LIKE '" + filterValue + "%'";
                case "ENDS_WITH_CASE_SENSITIVE":
                    return " " + filterDataField + " LIKE '%" + filterValue + "'" + "  ";
                case "ENDS_WITH":
                    return " " + filterDataField + " LIKE '%" + filterValue + "'";
            }
            return "";
        }

        private List<BestBuyQTYLogsDetailViewModel> GetQtyLogsDynamicQuery(string query)
        {


            token = Request.Cookies["Token"];
            List<BestBuyQTYLogsDetailViewModel> listModel = new List<BestBuyQTYLogsDetailViewModel>();
            listModel = _dropshipQtyMovementApiAccess.GetBestBuyDropshipQty(ApiURL, token, query);
            //List<BestBuyQTYLogsDetailViewModel> listModel = null;
            //try
            //{
            //    using (MySqlConnection conn = new MySqlConnection(connectionString))
            //    {
            //        conn.Open();
            //        MySqlCommand cmd = new MySqlCommand(query+ " Order by order_date desc", conn);
            //        MySqlDataAdapter da = new MySqlDataAdapter(cmd);
            //        DataTable dataTable = new DataTable();
            //        da.Fill(dataTable);
            //        if (dataTable.Rows.Count > 0)
            //        {
            //            listModel = new List<BestBuyQTYLogsDetailViewModel>();
            //            foreach (DataRow dataRow in dataTable.Rows)
            //            {

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/BestBuyDropshipQtyMovement/AllDropshipQtyMovementList.cshtml
@{
    ViewData["Title"] = "BestBuy Qty Update Log";
    Layout = "~/Views/Shared/_LayoutNavigation.cshtml";
}


<h6>BestBuy Qty Update Log</h6>


@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script type="text/javascript">
        $(document).ready(function () {
        //var showLink = function (row, datafield, value) {
        //    return '<a href="/BestBuyProduct/PropertyPage?ProductSKU=' + value + '" target="_blank">' + value + '</a>';
        //}
        //var showBBLink = function (row, datafield, value) {
        //    if (value != "") {
        //        return '<a href="https://marketplace.bestbuy.ca/mmp/shop/offer?productId=' + value + '" target="_blank">' + value + '</a>';
        //    }

        //}
           var source =
            {
                datatype: "json",
                datafields: [
                    { name: 'order_date', type: 'date' },
                    { name: 'product_sku' },
                    { name: 'BBProductID' },
                    { name: 'ds_qty' },
                    { name: 'ds_status' },
                    { name: 'update_status' },
                    { name: 'comments' },
                    { name: 'bb_import_id' }
                   

                ],
                url: '@Url.Action("GetQtyLogs", "BestBuyDropshipQtyMovement")',
                filter: function () {
                    // update the grid and send a request to the server.
                    $("#quantityDiv").jqxGrid('updatebounddata', 'filter');
                }
            };



         var dataAdapter = new $.jqx.dataAdapter(source);
            // initialize jqxGrid
        $("#quantityDiv").jqxGrid(
                {
                    source: dataAdapter,
                    filterable: true,
                    showfilterrow: true,
                    selectionmode: 'multiplecellsextended',
                    showfilterrow: true,
                   
                    pageable: true,
                    pagesize: 25,
                    width: '90%',
                    sortable: true,
                    altrows: true,
                    enabletooltips: true,
                    editable:true,
                    height:'900px',
                    ready: function () {
                        //$("#jqxgrid").find('.jqx-grid-column-header .jqx-checkbox-default').parent().on('change', function (event) {
                        //    var state = event.args.checked;
                        //    alert(state);
                        //});

                    },
                    autoshowfiltericon: true,
                    columns: [

                        {
                            text: 'SKU', datafield: 'product_sku', editable: false, filtertype: 'input', columntype: 'textbox', width: 200,  cellsrenderer: function (row)
                            {
                                var ProductSku = dataAdapter.records[row].product_sku;
                                return '<a  href="/BestBuyProduct/PropertyPage?ProductSKU=' + ProductSku + '"  target="_blank"  >' + ProductSku + '</a>';
                            }
                        },
                        {
                            text: 'BB Product ID', datafield: 'BBProductID', editable: false, columntype: 'textbox', filtertype: 'input', width: 200, cellsrenderer: function (row)
                            {
                                var BBProductID = dataAdapter.records[row].BBProductID;
                                return '<a  href="https://marketplace.bestbuy.ca/mmp/shop/offer?productId=' + BBProductID + '"  target="_blank">' + BBProductID + '</a>';
                            }
                        },
                        {
                            text: 'DS Qty', datafield: 'ds_qty', editable: false, padding: 5, columntype: 'textbox', filtertype: 'input', width: 200 
                              
                        },
                        { text: 'DS Status', datafield: 'ds_status', columntype: 'textbox', filtertype: 'input' , width: 200 },

                        {
                            text: 'Update Date & Time', datafield: 'order_date', filtertype: 'range', cellsformat: 'yyyy-MM-dd hh:MM tt', width: 200 
                        },

                        {
                            text: 'Status', datafield: 'update_status', columntype: 'textbox', filtertype: 'input', width: 200
                        },
                        {
                            text: 'Comments', datafield: 'comments', columntype: 'textbox', filtertype: 'input', width: 200
                        },
                        {
                            text: 'Import ID', datafield: 'bb_import_id', columntype: 'textbox', filtertype: 'input', width: 200
                        }


                    ]
                });
        });
    </script>

    @*<jqx-grid sortable="true"  enable-tool-tips="true"   show-filter-row="true" width="90%"   pageable="true" page-size="50" filterable="true" auto-height="false" height="1000px" source="Model">
            <jqx-grid-columns>
                <jqx-grid-column width="150px" filter-type="input" datafield-for="@(employee.ProductSku)" cells-renderer="showLink()" text="SKU">
                </jqx-grid-column>
                <jqx-grid-column width="150px" filter-type="input" datafield-for="@(employee.BBProductID)" cells-renderer="showBBLink()" text="BB Product ID">
                </jqx-grid-column>

                <jqx-grid-column datafield-for="@(employee.DropShipQuantity)" text="DS Qty"></jqx-grid-column>
                <jqx-grid-column filter-type="list" datafield-for="@(employee.DropShipStatusString)" text="DS Status"></jqx-grid-column>
                <jqx-grid-column width="150px" filter-type="range" datafield-for="@(employee.OrderDate)" cells-format="yyyy-MM-ddTHH:mm:ss.fff" text="Update Date & Time"></jqx-grid-column>
                <jqx-grid-column datafield-for="@(employee.IsDropshipStatusUpdate_Name))" text="Status"></jqx-grid-column>
                <jqx-grid-column datafield-for="@(employee.comments)" width="150px" text="Comments"></jqx-grid-column>
                <jqx-grid-column datafield-for="@(employee.BestBuyImportID)"  text="Import ID"></jqx-grid-column>
            </jqx-grid-columns>
        </jqx-grid>*@

    <div id="quantityDiv"></div>
}

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/BestBuyDropshipQtyMovement/BestBuyDropshipQtyMovementParitalView.cshtml
@model PagedList.IPagedList<Hld.WebApplication.ViewModel.BestBuyQTYLogsDetailViewModel>
@using Hld.WebApplication.Helper

@inject Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnv
@using Microsoft.AspNetCore.Authorization
@inject IAuthorizationService AuthorizationService
<style type="text/css">


    .table-bordered thead th, .table-bordered thead td {
        padding: 0px;
        border-bottom-width: 2px;
    }
    .table.tablesorter tbody tr:hover td {
        background: #f1f1f1;
        cursor: pointer;
    }
    .table thead th {
        vertical-align: middle !important;
        border-bottom: 2px solid #DEE2E6;
        text-align: center;
    }

    .table th, .table td {
        padding: 0.40rem;
        vertical-align: top;
        border-top: 1px solid #DEE2E6;
        vertical-align: middle !important;
    }

    .table tbody tr:hover {
        background-color: #F5F5F5;
    }

    .table td {
        text-align: left;
    }

    .table thead tr th {
        position: sticky;
        top: 168px;
        padding: 5px;
        text-align:left;
        z-index: 2;
        background-color: lightgray;
    }


    .tablesorter-default .tablesorter-header {
        outline: none !important;
    }

    .table {
        border-left: #ccc 1px solid !important;
        border-right: #ccc 1px solid !important;
    }
</style>
<div class="container-fluid">
    <table class="table tablesorter mytable" style="margin-top:174px;width:98%!important">


        <thead style="background-color:lightgray;">
            <tr>
                <th>SKU</th>
                <th>BB Product ID</th>
                <th>
                    DS Qty
                </th>

                <th>
                    DS Status
                </th>
                <th>
                    Created On
                  
                </th>
                <th>
                    Updated On BB
                </th>
                <th>
                    @*Updated On BB*@
                    Status
                </th>
            </tr>
        </thead>
        <tbody>

            @foreach (var item in Model)
            {
            <tr>
                <td>
                    <a style="padding-left:18px;cursor:pointer" asp-action="PropertyPage" asp-controller="BestBuyProduct" asp-route-ProductSKU="@item.product_sku" target="_blank">@item.product_sku</a>

                </td>
                <td>

                    <a href="https://marketplace.bestbuy.ca/mmp/shop/offer?productId=@item.BBProductID" target="_blank">@item.BBProductID</a>
                </td>
                <td>
                    @item.ds_qty
                </td>

                <td>

                    @{
                        if (item.ds_status == "1")
                        {
                            <span>DropShip</span>
                        }
                        else
                        {<span>DropShip None</span>

                        }
                    }
                </td>
                <td>
                    @if (@item.order_date != DateTime.MinValue)
                    {
                        @string.Format("{0: MMM d, yyyy HH:mm:ss}", @item.order_date)}

                </td>
                <td>
                    @if (@item.UpdatedOnBB != DateTime.MinValue)
                    {
                        @string.Format("{0: MMM d, yyyy HH:mm:ss}", @item.UpdatedOnBB)}

                </td>
                <td>
                    @{
                        if (item.update_status == "1")
                        {
                            <span>Updated</span>
                        }
                        else
                        {<span>Pending</span>

                        }
                    }

                </td>
            </tr>
            }
        </tbody>
    </table>

</div>