Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Controllers/ZincController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using Hld.WebApplication.Enum;
using Hld.WebApplication.Helper;
using Hld.WebApplication.ViewModel;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using PagedList.Core;
using ServiceReference1;
using static Hld.WebApplication.ViewModel.SaveZincOrders;

namespace Hld.WebApplication.Controllers
{
    [TokenExpires]
    public class ZincController : Controller
    {
        private readonly IConfiguration _configuration;
        string ApiURL = "";
        string token = "";
        string ZincUserName = "";
        string request_succeeded = "";
        string request_failed = "";
        string tracking_obtained = "";
        string s3BucketURL = "";
        string s3BucketURL_large = "";
        string SCRestURL = "";
        ServiceReference1.AuthHeader authHeader = null;
        BBProductApiAccess _bBProductApiAccess = null;
        ProductApiAccess _productApiAccess = null;
        ZincApiAccess _zincApiAccess = null;
        public static IHostingEnvironment _environment;
        ZincOrderLogAndDetailApiAccess _zincOrderLogAndDetailApiAccess = null;
        SellerCloudApiAccess _sellerCloudApiAccess = null;
        EncDecChannel _encDecChannel = null;

        GetChannelCredViewModel _Selller = null;
        GetChannelCredViewModel _Zinc = null;
        GetChannelCredViewModel ZincDays = null;
        OrderNotesAPiAccess _OrderApiAccess = null;
        public ZincController(IConfiguration configuration, IHostingEnvironment environment)
        {
            _environment = environment;
            this._configuration = configuration;
            ApiURL = _configuration.GetValue<string>("WebApiURL:URL");
            s3BucketURL = _configuration.GetValue<string>("S3BucketURL:URL");
            s3BucketURL_large = _configuration.GetValue<string>("S3BucketURL:L_URL");
            _bBProductApiAccess = new BBProductApiAccess();
            _productApiAccess = new ProductApiAccess();
            _sellerCloudApiAccess = new SellerCloudApiAccess();
            _zincApiAccess = new ZincApiAccess();
            _zincOrderLogAndDetailApiAccess = new ZincOrderLogAndDetailApiAccess();
            request_succeeded = _configuration.GetValue<string>("WebhooksUrl:request_succeeded");
            request_failed = _configuration.GetValue<string>("WebhooksUrl:request_failed");
            tracking_obtained = _configuration.GetValue<string>("WebhooksUrl:tracking_obtained");
            _OrderApiAccess = new OrderNotesAPiAccess();
            _encDecChannel = new EncDecChannel();
            SCRestURL = _configuration.GetValue<string>("WebApiURL:SCRestURL");
        }


        public IActionResult Index(string sku)
        {
            token = Request.Cookies["Token"];
            List<ZincProductSaveViewModel> listViewModel = _zincApiAccess.GetZincASINBySKU(ApiURL, token, sku);
            return PartialView("~/Views/Zinc/_Index.cshtml", listViewModel);
        }
        public IActionResult ProductZinc(string ProductSKU)
        {
            token = Request.Cookies["Token"];
            TempData["ProductSKU"] = ProductSKU;
            int productID = 0;
            productID = _productApiAccess.GetProductIDBySKU(ApiURL, token, ProductSKU);
            BBProductViewModel model = _bBProductApiAccess.GetBestBuyProductDetail_ProductID(ApiURL, token, ProductSKU);
            return View(model);

        }

        public int ZincJobExecute()
        {
            token = Request.Cookies["Token"];
            _productApiAccess.ExecuteJobs(ApiURL, token);
            return 0;
        }

        [HttpGet]
        public IActionResult ZincSetting()
        {
            return View();
        }

        [HttpPost]
        public IActionResult ZincSetting(string info)
        {
            return View();
        }
        //Mueen
        [HttpPost]
        public async Task<IActionResult> SubmitOrderToZinc(string ZincOrderdata, string orderDateTimeShip, int CreditCardId, int ZincAccountId, int DeliveryDays)
        {
            try
            {
                token = Request.Cookies["Token"];
                CreditCardApiAccess creditCardApiAccess = new CreditCardApiAccess();
                SaveZincOrders.RootObject ZincOrder = new SaveZincOrders.RootObject();
                ZincOrder = JsonConvert.DeserializeObject<SaveZincOrders.RootObject>(ZincOrderdata);
                _Selller = new GetChannelCredViewModel();
                _Selller = _encDecChannel.DecryptedData(ApiURL, token, "sellercloud");
                AuthenticateSCRestViewModel authenticate = _OrderApiAccess.AuthenticateSCForIMportOrder(_Selller, SCRestURL);
                if (DeliveryDays > 0)
                {
                    ZincOrder.shipping.max_days = DeliveryDays;
                }

                int _zincOrderLogID = 0;
                int SellerCloudOrderID = 0;
                string RequestID = "";
               
                var CreditCardDetail = creditCardApiAccess.GetCreditCardDetailById(ApiURL, token, CreditCardId);
                var AccountDetail = creditCardApiAccess.GetAccountDetailById(ApiURL, token, ZincAccountId);
                _Zinc = new GetChannelCredViewModel();
                ZincOrder.retailer_credentials = new SaveZincOrders.RetailerCredentials();
                ZincOrder.retailer_credentials.email = _encDecChannel.DecryptStringFromBytes_Aes(AccountDetail.UserName);
                ZincOrder.retailer_credentials.password = _encDecChannel.DecryptStringFromBytes_Aes(AccountDetail.Password);
                ZincOrder.retailer_credentials.totp_2fa_key = _encDecChannel.DecryptStringFromBytes_Aes(AccountDetail.Key);
                ZincOrder.payment_method = new SaveZincOrders.PaymentMethod();
                ZincOrder.payment_method.use_gift = false;
                ZincOrder.payment_method.name_on_card = CreditCardDetail.first_name + " " + CreditCardDetail.last_name;
                ZincOrder.payment_method.number = _encDecChannel.DecryptStringFromBytes_Aes(CreditCardDetail.number);
                ZincOrder.payment_method.security_code = _encDecChannel.DecryptStringFromBytes_Aes(CreditCardDetail.security_code);
                ZincOrder.payment_method.expiration_month = Convert.ToInt32(CreditCardDetail.expiration_month);
                ZincOrder.payment_method.expiration_year = Convert.ToInt32(CreditCardDetail.expiration_year);
                ZincOrder.billing_address = new SaveZincOrders.BillingAddress();
                ZincOrder.billing_address.address_line1 = CreditCardDetail.address_line1;
                ZincOrder.billing_address.address_line2 = CreditCardDetail.address_line2;
                ZincOrder.billing_address.city = CreditCardDetail.city;
                ZincOrder.billing_address.country = CreditCardDetail.country;
                ZincOrder.billing_address.first_name = CreditCardDetail.first_name;
                ZincOrder.billing_address.last_name = CreditCardDetail.last_name;
                ZincOrder.billing_address.phone_number = CreditCardDetail.PhoneNo;
                ZincOrder.billing_address.state = CreditCardDetail.state;
                ZincOrder.billing_address.zip_code = CreditCardDetail.zip_code;
                ZincOrder.webhooks = new Webhooks();
                ZincOrder.webhooks.request_succeeded = request_succeeded;
                ZincOrder.webhooks.request_failed = request_failed;
                ZincOrder.webhooks.tracking_obtained = tracking_obtained;
                //  ZincOrder.webhooks = _webhooks;
                token = Request.Cookies["Token"];
                //Commented By me
                SellerCloudOrderID = ZincOrder.client_notes.our_internal_order_id;
                RequestID = SubmitOrderToZincForSave(ZincOrder);
                if (RequestID != string.Empty)
                {
                    bool status = false;
                    CreateNotesViewModel createNotesView = new CreateNotesViewModel();
                    UpdateSCDropshipStatusViewModel updateSCViewModel = new UpdateSCDropshipStatusViewModel();
                    List<CreateOrderNotesViewModel> data = new List<CreateOrderNotesViewModel>();
                    updateSCViewModel.StatusName = "Requested";
                    updateSCViewModel.SCOrderID = ZincOrder.client_notes.our_internal_order_id;
                    updateSCViewModel.LogDate = DatetimeExtension.ConvertToEST(DateTime.Now);
                    createNotesView.Message = "RequestId: " + RequestID;
                    createNotesView.Category = "0";
                    _OrderApiAccess.CreateOrderNotesFormSC(SCRestURL, authenticate.access_token, updateSCViewModel.SCOrderID, createNotesView);
                    List<CreateOrderNotesViewModel> getNotes = _OrderApiAccess.GetOrderNotesFormSC(SCRestURL, authenticate.access_token, updateSCViewModel.SCOrderID);
                    if (getNotes.Count > 0)
                    {
                        data = (List<CreateOrderNotesViewModel>)getNotes.Select(p => p).Where(p => p.NoteID != 0).ToList();
                        if (data.Count > 0)
                        {
                            status = _OrderApiAccess.saveOrderNotes(ApiURL, token, data);
                            if (status == true)
                            {
                                _OrderApiAccess.SetOrderHavingNotes(ApiURL, token, Convert.ToInt32(updateSCViewModel.SCOrderID));
                            }
                        }
                    }
                    // UpdateScOrderToDs updateSc = new UpdateScOrderToDs();
                    var getOrderId = new UpdateScOrderToDs()
                    {
                        Orders = new List<int>
                        {

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/BestBuyUpdateLogs/BustBuuPartialView.cshtml
@model PagedList.Core.IPagedList<Hld.WebApplication.ViewModel.BestBuyUpdateLogsViewModel>
@using Hld.WebApplication.Helper
@*@model IEnumerable<Hld.WebApplication.ViewModel.BestBuyOrdersViewModel>*@
@inject Microsoft.AspNetCore.Hosting.IHostingEnvironment hostingEnv

<style>
    tr.detail {
        display: none;
        width: 100%;
    }

    .hidden_row {
        display: none;
    }

    .showmore:hover {
        cursor: pointer;
    }

    .preappendlist {
        height: 26px;
        padding: 0px;
    }

    .cmclass {
        /*width: 60px;*/
        box-shadow: none;
    }

    .form-control {
        box-shadow: none !important;
    }

    .input-group {
        position: relative;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-wrap: wrap;
        flex-wrap: wrap;
        -ms-flex-align: stretch;
        align-items: stretch;
        width: 99% !important;
    }

    .btndivstyle {
        width: 260px !important;
        min-width: 260px !important;
        padding: 6px !important;
        margin-right: 2px !important;
        border-radius: 3px !important;
    }

    .btnsave {
        outline: none !important;
        box-shadow: none !important;
    }

    .btncancel {
        outline: none !important;
        box-shadow: none !important;
    }

    .table {
        border-left: #ccc 1px solid !important;
        border-right: #ccc 1px solid !important;
        border-bottom: #ccc 1px solid !important;
        cursor: pointer !important;
    }

        .table thead tr th {
            position: sticky;
            top: 50px;
            padding: 5px;
            z-index: 2;
            background-color: lightgray !important;
        }
</style>

<table class="table">
    <thead class="thead-light">
        <tr>
            @*<th data-sorter="false">
            <input type="checkbox" id="headerCheckBox" />
        </th>*@
            <th>
                Image
            </th>
            <th>
                Product SKU
            </th>
            <th>
                ASIN
            </th>
            <th>
                Job ID #
            </th>

            <th>Updated Selling Price</th>

            <th>MSRP Price</th>
            <th>
                Import ID
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            @*<td>
            <input class="checkboxSkuForUpdating checkboxSkForEnableDisable "  type="checkbox" />
        </td>*@
            <td>
                @{
                    <a target="_blank" href="@ViewBag.S3BucketURL_large/@item.image_name">
                        <img src="@ViewBag.S3BucketURL/@item.Compress_image" class="rounded" height="50" width="50" />
                    </a>
                }
            </td>
            <td>
                <span><a style="cursor:pointer" asp-action="ProductZinc" asp-controller="Zinc" asp-route-productsku="@item.SKU" target="_blank">@item.SKU</a></span><br />
                <a style="padding-left:2px;cursor:pointer" asp-action="ProductZinc" asp-controller="Zinc" asp-route-ProductSKU="@item.SKU" target="_blank">
                    <img height="13px" width="15px" src="~/Images/zinc.png" />
                </a>
                <a style="padding-left:5px;cursor:pointer" href="https://lp.cwa.sellercloud.com/Inventory/Product_Dashboard.aspx?Id=@item.SKU" target="_blank">
                    <img height="13px" width="15px" src="~/Images/sellercloud-gray.png" />
                </a>
                <a style="padding-left:2px;cursor:pointer" href="https://www.bestbuy.ca/en-ca/search?search=+@item.ProductId" target="_blank">
                    <img height="10px" width="15px" src="~/Images/openbb.png" />
                </a>
                <a style="padding-left:2px;cursor:pointer" href="https://marketplace.bestbuy.ca/mmp/shop/offer?productId=@item.ProductId" target="_blank">
                    <img height="13px" width="15px" src="~/Images/BestBuy-Gray.png" />
                </a>
            </td>
            <td>
                @*@Html.DisplayFor(modelItem => item.ASIN)*@
                <a href="https://www.amazon.ca/dp/@item.ASIN" target="_blank">@item.ASIN</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JobId)
            </td>
            <td>
                @item.UpdateSelllingPrice

            </td>
            <td>

                @item.MSRP


            </td>
            <td>
                @Html.DisplayFor(modelItem => item.importId)
            </td>
        </tr>
        }
    </tbody>
</table>

Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Hld.WebApplication/Views/BestBuyUpdateLogs/Index.cshtml
@{
    ViewData["Title"] = "BestBuyLogs";
    Layout = "~/Views/Shared/_LayoutNavigation.cshtml";
}
<link href="~/select2/css/select2.min.css" rel="stylesheet" />
<style>
    .pagination > a {
        padding: 5px;
    }

    .myclass {
        position: fixed;
        top: 20%;
        left: 70%;
        color: green;
        transform: translate(-50%, -50%);
        box-sizing: border-box;
        padding: 60px;
    }

    .select2-container {
        box-sizing: border-box;
        display: inline-block;
        margin: 0;
        width: 215px !important;
        position: relative;
        vertical-align: middle;
    }

    .btngocalss {
        box-shadow: none !important;
        border: none !important;
        height: 28px !important;
        margin-left: -6px !important;
        border-radius: 5px !important;
    }

    .mydlete {
        position: fixed;
        top: 24%;
        left: 70%;
        color: red;
        transform: translate(-50%, -50%);
        box-sizing: border-box;
        padding: 60px;
    }

    .myclass {
        position: fixed;
        top: 24%;
        left: 70%;
        color: green;
        transform: translate(-50%, -50%);
        box-sizing: border-box;
        padding: 30px;
    }

    .loader {
        position: fixed;
        left: 0px;
        top: 0px;
        width: 100%;
        height: 100%;
        z-index: 9999;
        opacity: .9;
        background-color: rgb(249,249,249);
    }

        .loader img {
            top: 50%;
            position: absolute;
            left: 50%;
            margin: 0;
            margin-right: -50%;
            transform: translate(-50%,-50%);
        }
</style>

<div class="loader">
    <img src="~/Images/giffff.gif" />
</div>
<div class="container-fluid p-0">
    <h6 style="margin-left: 13px;">BestBuy Logs</h6>
    <div class="row col col-12" id="fixActionMenu">
        <div class="col col-md-2">
            <div class="row">
                <div class="pagination col-md-6 col" style="margin-left: 10px;">

                </div>

            </div>
        </div>
        <div class="col col-md-2">
            <span>Records Found : @ViewBag.logsRecords</span>
        </div>
    </div>
</div>
<div class="container-fluid">
    <div id="loadOrder">

    </div>
</div>
<div class="container-fluid">
    <div class="pagination">

    </div>
</div>
@section Scripts{
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script src="~/lib/jQuery-Paging/jquery.paging.min.js"></script>
    <script src="~/select2/js/select2.full.min.js"></script>
    <script type="text/javascript">

        $(document).ready(function () {
            $(".loader").hide();
            $(document).on('click', '#headerCheckBox', function () {


                if ($(this).is(':checked')) {

                    $(".table tbody tr ").each(function () {
                        debugger;
                        var watchlistsku = $(this).find('.watchlistdata').val();
                        console.log("watlhust", watchlistsku);
                        if (watchlistsku == 1) {
                            $(this).find('.checkboxSkForEnableDisable').attr('checked', true);
                        }
                    });
                }
                else {

                    $(".table tbody tr ").each(function () {
                        $(this).find('.checkboxSkForEnableDisable').attr('checked', false);
                    });
                }
            });


            $("#actionMenu").select2();
            function hideclass() {
                $(".btnbuttonstyle").hide();

            }
            $(document).on("dblclick", ".inputvalchange", function () {
                $(".btnbuttonstyle").hide();

                // $(this).closest('tr').find(".buttons-group").css("transform", "translateX(0)");

                $(this).closest('tr').find(".btnbuttonstyle").show();



            })

$(document).on("click", ".btnsavetable", function () {
//var selectedRow = $(this);
//var productid = $(selectedRow).parents('tr').find('.idZincProxy').val();
var asin = $(this).closest('tr').find(".inputvalchange").attr("data-id");
var maxprice = $(this).closest('tr').find(".inputvalchange").val();
console.log("price get", maxprice);
console.log("asin value", asin);

$.ajax({
type: 'GET',
url: '../ZincWatchlist/UpdatePriceMax',
data: {
ASIN: asin,
MaxPrice: maxprice
},
success: function (data) {
//$("#dialog-Delete").dialog("close");
//$(".loader").hide();
//selectedRow.parents('tr').remove();
$.notify('update Successfully', { globalPosition: 'bottom right', className: 'danger myclass' });
},
Error: function (err) {

}
});

});

            $(document).on("click", ".btncanceltable", function () {
                $(".btnbuttonstyle").hide();


            })


$(document).on("dblclick", ".inputvalchange", function () {
$(this).closest('tr').find(".btnsavetable").show();

$(this).closest('tr').find(".btncanceltable").show();


})
              var getUrlParameter = function getUrlParameter(sParam) {
                var sPageURL = window.location.search.substring(1),
                    sURLVariables = sPageURL.split('&'),
                    sParameterName,
                    i;

                for (i = 0; i < sURLVariables.length; i++) {
                    sParameterName = sURLVariables[i].split('=');

                    if (sParameterName[0] === sParam) {
                        return sParameterName[1] === undefined ? true : decodeURIComponent(sParameterName[1]);
                    }
                }
            };
            var jobID = getUrlParameter('JobId');

            $.fn.checkUncheckSKU_checkbox = function (status) {
                $(document).find('.checkboxSkuForUpdating').each(function (index) {
                    $(this).attr('checked', status);
                });
            }

          //pagination
                $(".pagination").paging(parseInt('@ViewBag.logsRecords'), {
                format: '[< nncnn >]',
                perpage: 25, // show 10 elements per page
                lapping: 0, // don't overlap pages for the moment
                page: 1, // start at page, can also be "null" or negative
                stepwidth: 0, // =0 means blockwise next/prev steps
                onSelect: function (page) {

                pageNo = page;
                // add code which gets executed when user selects a page

                    var url = '/BestBuyUpdateLogs/getlist?page=' + page + ''
                    var completURL = '/BestBuyUpdateLogs/getlist?page=' + page + '&JobId=' + jobID;
                $(".loadertbl").show();

                    $.ajax({
                        url: completURL,
                        data: {},
                        type: 'POST',
                        traditional: true,
                        success: function (data) {
                            $('#loadOrder').empty();
                            $('#loadOrder').html(data);
                            hideclass();
                            $(".loadertbl").hide();
                            // $('#tableOrderList').stickyTableHeaders({ fixedOffset: 0 });
                        }
                    });
                    if (typeof OrderDateTimeFrom !== "undefined" && typeof OrderDateTimeTo !== "undefined") {
                        if (OrderDateTimeFrom !== "" && OrderDateTimeTo !== "") {
                            start = moment(OrderDateTimeFrom);
                            end = moment(OrderDateTimeTo);

                            cb(moment(OrderDateTimeFrom), moment(OrderDateTimeTo));
                        }
                        else {
                            $('#reportrange span').html("No Date Selected");
                        }

                    }
                    else {
                        $('#reportrange span').html("No Date Selected");
                    }
                },
                    onFormat: function (type) {
                        switch (type) {
                            case 'block': // n and c
                                if (this.page === this.value) {
                                    return '<span>' + this.value + '</span>';
                                } else {
                                    return '<a href="#">' + this.value + '</a>';
                                }
                            case 'next': // >
                                return '<a href="#">&gt;</a>';
                            case 'prev': // <
                                return '<a href="#">&lt;</a>';
                            case 'first': // [
                                return '<a href="#">First</a>';
                            case 'last': // ]
                                return '<a href="#">Last</a>';
                        }
                    }


                });


        });




    </script>
}